# Q-1

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1.reshape([2,3])

array([[1, 2, 3],
       [4, 5, 6]])

# Q-2

In [9]:
arr1=np.array([1,2,3,2,3,4,3,4,5,6])
arr2=np.array([7,2,10,2,7,4,9,4,9,8])
print("Original arrays :",arr1,arr2)
arr3=np.intersect1d(arr1,arr2)
print("Common values :",arr3)

Original arrays : [1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]
Common values : [2 4]


# Q-3

In [20]:
arr1=np.array([2,6,1,9,10,3,27])
print("Original array :",arr1)
arr2=arr1[(arr1>=5) & (arr1<=10)]
print("Numbers between 5 to 10 are :",arr2)

Original array : [ 2  6  1  9 10  3 27]
Numbers between 5 to 10 are : [ 6  9 10]


# Q-4

In [23]:
arr1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
np.set_printoptions(threshold=6)
print(arr1)

[ 0  1  2 ... 12 13 14]


# ASSIGNMENT QUESTIONS:
# How to create an empty and a full numpy array

In [69]:
import numpy as np
a=np.empty((4,3,2))
print("Empty array =",a)

Empty array = [[[6.23042070e-307 1.86918699e-306]
  [1.69121096e-306 6.23058707e-307]
  [8.45593934e-307 7.56593017e-307]]

 [[1.11261027e-306 1.11261502e-306]
  [1.42410839e-306 7.56597770e-307]
  [6.23059726e-307 1.42419530e-306]]

 [[7.56602523e-307 1.29061821e-306]
  [1.37961234e-306 9.34598926e-307]
  [1.33511562e-306 9.34600963e-307]]

 [[8.45559303e-307 9.45697982e-308]
  [1.33511562e-306 8.90103560e-307]
  [1.42410974e-306 8.73989989e+247]]]


In [3]:
b=np.full((2,2),7)
print("Full array =",b)

Full array = [[7 7]
 [7 7]]


# Create a numpy array filled with all zeros

In [6]:
a=np.zeros((4,3))
print("Zeros array =",a)

Zeros array = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Create a numpy array filled with all ones

In [31]:
b=np.ones((4,3))
print("Ones array =",b)

Ones array = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Check whether a numpy array contains a specified row

In [36]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

a = np.array([4, 5, 6])

b = np.any(np.all(array == a, axis=1))

if b:
    print("The specified row exists in the array.")
else:
    print("The specified row does not exist in the array.")

The specified row exists in the array.


# How to remove rows in numpy array that contains non-numeric values

In [39]:
arr1 = np.array([[1, 2, 'g', 3], [4, 8, 5, 6], [7, 8, 'i', 9]])

remove = [0, 2]

arr2 = np.delete(arr1, remove, axis=0)

print("Original Array:")
print(arr1)
print("\nArray after removing specified rows:")
print(arr2)

Original Array:
[['1' '2' 'g' '3']
 ['4' '8' '5' '6']
 ['7' '8' 'i' '9']]

Array after removing specified rows:
[['4' '8' '5' '6']]


# Remove singal dimensional entries from the shape of an array

In [42]:
arr1 = np.array([[[1, 2, 3]]])

print("Original Shape:", arr1.shape)

arr2 = np.ravel(arr1)

print("Shape after changing:", arr2.shape)

Original Shape: (1, 1, 3)
Shape after changing: (3,)


# Find the number of occurences of a sequence in a numpy array

In [47]:
arr = np.array([[2, 8, 9, 4], 
                [9, 4, 9, 4], 
                [4, 5, 9, 7], 
                [2, 9, 4, 3]]) 
 
arr2 = repr(arr).count("9, 4") 

print("Number of occurences of a sequence is",output) 


Number of occurences of a sequence is 4


# Find the most frequent value in a numpy array

In [63]:
arr = np.array([1,2,1,3,6,2,5,1,2,2,3,2,2,5,2,4,2,6,2,5,1,6])
print("Original array =",arr)
arr2 = np.bincount(arr).argmax()
print("Most frequent value in the above array is ",arr2)

Original array = [1 2 1 3 6 2 5 1 2 2 3 2 2 5 2 4 2 6 2 5 1 6]
Most frequent value in the above array is  2


# Combining a one and a two dimensional numpy array

In [68]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],
               [5,6,7,8]])
arr3=np.vstack([arr1,arr2])
print(arr3)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


# How to build an array of all combinations of two numpy arrays

In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array(['a', 'b', 'c'])

grid1, grid2 = np.meshgrid(arr1, arr2)

arr3 = np.column_stack((grid1.ravel(), grid2.ravel()))

print("Array 1:",arr1)

print("\nArray 2:",arr2)

print("\nCombined array of all combinations:",arr3)

Array 1: [1 2 3]

Array 2: ['a' 'b' 'c']

Combined array of all combinations: [['1' 'a']
 ['2' 'a']
 ['3' 'a']
 ['1' 'b']
 ['2' 'b']
 ['3' 'b']
 ['1' 'c']
 ['2' 'c']
 ['3' 'c']]
