# Q-1

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1.reshape([2,3])

array([[1, 2, 3],
       [4, 5, 6]])

# Q-2

In [9]:
arr1=np.array([1,2,3,2,3,4,3,4,5,6])
arr2=np.array([7,2,10,2,7,4,9,4,9,8])
print("Original arrays :",arr1,arr2)
arr3=np.intersect1d(arr1,arr2)
print("Common values :",arr3)

Original arrays : [1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]
Common values : [2 4]


# Q-3

In [20]:
arr1=np.array([2,6,1,9,10,3,27])
print("Original array :",arr1)
arr2=arr1[(arr1>=5) & (arr1<=10)]
print("Numbers between 5 to 10 are :",arr2)

Original array : [ 2  6  1  9 10  3 27]
Numbers between 5 to 10 are : [ 6  9 10]


# Q-4

In [23]:
arr1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
np.set_printoptions(threshold=6)
print(arr1)

[ 0  1  2 ... 12 13 14]
